In [1]:
import pandas as pd

In [6]:
edges_df = pd.read_csv('edges.csv')
nodes_df = pd.read_csv('nodes.csv')

In [7]:
edges_df.describe()

              source         target         weight
count  111526.000000  111526.000000  111526.000000
mean     4548.317576    4548.317576       1.542482
std      2666.222250    2666.222250       4.904134
min         0.000000       0.000000       0.497513
25%      1958.000000    1958.000000       0.596176
50%      5554.000000    5554.000000       0.768473
75%      6923.000000    6923.000000       1.194621
max      8504.000000    8504.000000     100.000000

In [8]:
nodes_df.describe()

,node_idx,latitude,longitude,resource_type,rating_normalized,wait_time_normalized,magnet_score,barrier_score,days_covered,poverty_index,subscriber_normalized,review_normalized,confidence,appointment_required,wait_bucket
count,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,8510.000000,4416.000000
mean,4254.500000,38.464994,-78.476180,0.111633,0.799813,0.275554,0.013220,0.087944,0.221941,0.174873,0.341158,0.214404,0.699558,0.077791,0.390625
std,2456.769729,3.969047,7.210521,0.359213,0.099777,0.222682,0.047304,0.154024,0.226166,0.126881,0.215614,0.230729,0.142699,0.267858,0.566560
min,0.000000,24.552151,-123.802787,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2127.250000,38.331577,-82.332281,0.000000,0.799813,0.041667,0.000000,0.000000,0.142857,0.073700,0.166460,0.000000,0.590000,0.000000,0.000000
50%,4254.500000,39.963304,-76.069232,0.000000,0.799813,0.233333,0.000000,0.000000,0.142857,0.147300,0.348883,0.125537,0.700000,0.000000,0.000000
75%,6381.750000,40.729326,-74.130945,0.000000,0.833333,0.500000,0.000000,0.200000,0.285714,0.249300,0.515343,0.397943,0.790000,0.000000,1.000000
max,8509.000000,47.864010,-69.546698,2.000000,1.000000,1.000000,0.500000,0.800000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000